gui:
  theme:
    activeBorderColor:
      - '#cba6f7'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#cba6f7'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b4befe'
  mouseEvents: true
  nerdFontsVersion: '3'
  mainPanelSplitMode: flexible
  commitLength:
    show: true
  splitDiff: auto
  spinner:
    frames:
      - "⣷ "
      - "⣯ "
      - "⣟ "
      - "⡿ "
      - "⢿ "
      - "⣻ "
      - "⣽ "
      - "⣾ "
    rate: 100
  statusPanelView: allBranchesLog
  commandLogSize: 2
  showRandomTip: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
  autoFetch: true
  autoRefresh: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: false
  log:
    order: topo-order
    showGraph: always
    showWholeGraph: false

update:
  method: prompt
  days: 14

refresher:
  refreshInterval: 10
  fetchInterval: 60

confirmOnQuit: false

os:
  editPreset: 'code'

customCommands:
  - key: 'b'
    command: 'gh browse'
    context: 'files'
  - key: 'b'
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: 'commits'
  - key: 'o'
    command: 'gh pr view --web'
    description: "View PR on GitHub"
    context: 'global'
  - key: 'o'
    command: 'gh pr view --web {{.SelectedLocalBranch.Name}}'
    description: "View PR on GitHub"
    context: 'localBranches'
    loadingText: 'Opening GitHub...'
    subprocess: false
  - key: 'F' 
    command: 'git push --force-with-lease --no-verify'
    context: 'localBranches'

notARepository: skip

promptToReturnFromSubprocess: true